run:
  skip-tests: true

issues:
  exclude-files:
    - "_test\\.go$"
  exclude-rules:
    - path: "_test\\.go$"
      linters:
        - "*"

linters-settings:
  gocritic:
    disabled-checkers:
      - exitAfterDefer
  revive:
    ignore-generated-header: true
  errcheck:
    check-type-assertions: true

linters:
  enable:
    - govet
    - revive
    - gosimple
    - misspell
  disable:
    - depguard
    - forbidigo
    - gocyclo
    - funlen
    - gocritic
    - goconst
    - unparam
    - unused
    - ineffassign
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - typecheck
