extends:
  - spectral:oas
  # - spectral:asyncapi # Let's remove this for now to simplify, assuming we only lint OpenAPI
rules:
  # Overrides from the original plan that turn things OFF
  openapi-tags-alphabetical: off
  contact-properties: off
  info-contact: off
  info-license: off
  license-url: off

  # Explicitly keep these as error, they are critical
  info-description: error
  operation-description: error
  operation-tags: error

  # We've fixed the swag regeneration issues, so these are now errors as intended
  operation-operationId: error
  operation-tag-defined: error

  # Let spectral:oas defaults handle other common error rules like:
  # operation-2xx-response, operation-4xx-response, path-params,
  # oas3-valid-schema-example, duplicate-path-parameter, openapi-tags etc.
  # by not listing them if their default is already 'error'.
