# Example Prometheus configuration for BalancedNewsGo

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'balancednewsgo'
    static_configs:
      - targets: ['localhost:9090'] # Update with your application's metrics endpoint