# Example Prometheus configuration for BalancedNewsGo

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'balancednewsgo'
    static_configs:
      - targets: ['${METRICS_TARGET}'] # Set your metrics endpoint via METRICS_TARGET env var
