name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod tidy

    # The project uses 'averaging everywhere' for LLM score calculation. All tests must pass.

    - name: Run Go unit and integration tests (NO_AUTO_ANALYZE=true)
      run: |
        export NO_AUTO_ANALYZE=true
        go test -v -coverprofile=coverage.out ./...

    - name: Run full API/integration test suite (scripts/test.sh all)
      if: runner.os == 'Linux'
      run: |
        chmod +x scripts/test.sh
        ./scripts/test.sh all

    - name: Upload test-results artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
    - name: Generate coverage summary
      run: |
        go tool cover -func=coverage.out -o coverage-summary.txt

    - name: Generate coverage badge
      uses: go-coverage/go-coverage-badge@v1.0.1
      with:
        coverage-file: coverage.out

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: |
          coverage.out
          coverage-summary.txt
          coverage-badge.svg

    # To enable OpenAI live integration test, uncomment and set these secrets or env vars:
    # env:
    #   LLM_PROVIDER: openai
    #   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    #   OPENAI_MODEL: gpt-3.5-turbo