name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod tidy

    # To enable OpenAI live integration test, uncomment and set these secrets or env vars:
    # env:
    #   LLM_PROVIDER: openai
    #   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    #   OPENAI_MODEL: gpt-3.5-turbo

    - name: Run tests
      run: go test -v ./...